name: Deploy into pages
description: Github Actions plugin for uploading static files into Github Pages
author: 'Max Rukomoynikov'

runs:
  using: node20
  main: dist/main.js

inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: true
  artifact_name:
    description: 'Name of the artifact to deploy'
    required: false
    default: 'github-pages'

outputs:
  page_url:
    description: 'URL to deployed GitHub Pages'
